var categories = {
  "access": "Access Software",
  "activision": "Activision",
  "ags": "Adventure Game Studio Games",
  "adventuresoft": "Adventure/Horror Soft",
  "animagic": "Animation Magic",
  "cloak": "Cloak & Dagger Games",
  "coktel": "Coktel Vision",
  "cyan": "Cyan Worlds",
  "delphine": "Delphine Software",
  "director": "Director Games",
  "dreamers": "Dreamers Guild",
  "dynamix": "Dynamix",
  "fan": "Fan Games",
  "gda": "Gray Design Associates",
  "her": "Her Interactive",
  "humongous": "Humongous Entertainment",
  "if": "Interactive Fiction",
  "incentive": "Incentive Software",
  "ita": "ITA-Choco", 
  "kd": "K-D Lab",
  "living": "Living Books",
  "lk": "L.K. Avalon",
  "lucasarts": "LucasArts",
  "composer": "Magic Tales",
  "mtropolis": "mTropolis Engine Games",
  "offstudio": "Off Studio",
  "magnetic": "Magnetic Scrolls",
  "origin": "Origin Systems",
  "other": "Other Games",
  "nwc": "New World Computing",
  "polarware": "Polarware",
  "presto": "Presto Studios",
  "revolution": "Revolution Studios",
  "schnibble": "Schnibble Productions",
  "sierra": "Sierra",
  "stranga": "Stranga",
  "synergy": "Synergy, Inc.",
  "tsunami": "Tsunami Games",
  "wadjet": "Wadjet Eye Games",
  "westwood": "Westwood Studios",
  "wintermute": "Wintermute Engine Games"
};
